# Generated by Django 4.2.10 on 2024-03-31 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_delete_reportfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.CreateModel(
            name="ReportFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="report_files/")),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="login.report",
                    ),
                ),
            ],
        ),
    ]
