# Generated by Django 4.2.10 on 2024-03-31 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_report_file_reportfile"),
    ]

    operations = [
        migrations.RemoveField(model_name="report", name="file",),
    ]
